### ISSUE TITLE
skos:broadMatch property missing for "other names" model

### ISSUE THREAD

**Issue by mit2nil** [american-art/ima#10]
Hi,

I was trying to model names_alt attribute of aac-actors.json data file using below reference model.
http://review.americanartcollaborative.org/entity/E39_Actor#field_7-search_0

Now, in the source data, we do not have <type_label> so we can not add the object of type crm:E55_Type. Doing so results, in adding simply another E82_Actor_Appellation class with rdf:value as alternate name values. But, doing so doesn't capture the fact that these are alternate names. 

I feel that there should be skos:broadMatch property in the reference model for crm:E55_Type object of Other Names. That's how it has been done in following variants of different models for names.
http://review.americanartcollaborative.org/entity/E39_Actor#field_2-search_0
http://review.americanartcollaborative.org/entity/E39_Actor#field_3-search_0
http://review.americanartcollaborative.org/entity/E39_Actor#field_4-search_0
http://review.americanartcollaborative.org/entity/E39_Actor#field_5-search_0
http://review.americanartcollaborative.org/entity/E39_Actor#field_6-search_0

Please let us know if we can go forward with current reference model or there is a need to update reference model or data to correctly represent this.  

Thanks
Nilay Chheda

**Comment by workergnome** [comment]
I think that it's deliberate that "alternate name" is just a name that is not primary.  If there's a semantic meaning to "alternate" beyond "not primary", I'd be happy to use that mapping, but if the only thing that distinguishes it is that it's an "alternate', I'm OK with the target model as is.

That being said, I'm not sure that I'm correct here.  @azaroth42, do you have a second opinion?

**Comment by SamiNorling** [comment]
I can confirm that "names_alt" has no semantic meaning in our data besides "not primary."

**Comment by SamiNorling** [comment]
I suggest that this issue be closed.
