### ISSUE TITLE
Reference model for actor_type attribute in aac-actors.json

### ISSUE THREAD

**Issue by mit2nil** [american-art/ima#12]
Hi,

How do we model "actor_type" attribute in the context of actor objects in aac-actors.json. Actors are modeled as a crm:E39_Actor and there is not aboutness objects/properties describing type of the top level object unlike E22_Man-Made_Object object which is used for art works and not the artists.

Nilay Chheda

**Comment by workergnome** [comment]
@IllyaMoskvin (or whomever is the correct person from IMA to look at this), can you clarify how this type is used and what sorts of values it has?  I don't know what "Registration-Verified" means, for example.

**Comment by IllyaMoskvin** [comment]
Sure thing. That field is pulled directly from our collections management system. Unfortunately, it appears to intermix workflow-related values with classifications. There's really only two actor types that are valid: "Artist" and "Organization".

To clarify: some of our objects have several actors associated with them. Typically, one of the actors is an artist of some type (e.g. "Artist", "Designer", "Painter"), and the other actors are organizations involved in the creation of the artwork (e.g. "Publishing House" or "Printer").

I'm pretty sure that we can write a script to deduce which of the two classifications each actor should have. Everything with a ULAN value should be an artist. Everything without is almost certainly an organization. Anything that has variations of designer, painter, and so on is an artist.

Are you guys differentiating between people and organizations in your mapping?

I have to go presently, but I'm working on a script to list all the unique values that field can take. I can get that your way, if it would be helpful.

P.S. Thank you for mentioning me. I was not watching this repository and did not notice the issues piling up. Will take a look at the backlog asap.

**Comment by workergnome** [comment]
We do have an explicit way to distinguish between people and organizations (E21 Person vs E40 Legal Body), so that would be helpful.  

Probably worth spot-checking the ULAN to make sure—I know ULAN has a bunch of institutions in it, so unless you're explicitly using that as a rule at IMA, it might not hold true.

**Comment by IllyaMoskvin** [comment]
I can try to write a script with that logic, but it's been a couple days, and in light of the hackathon, I just want to clarify whether or not the students already wrote that code, just so that I don't cover the same tracks. Additionally, can you guys tell me what you'd like me to name the (new) field for each actor that will be used to indicate if it's an `E21 Person` or `E40 Legal Body`?

**Comment by mit2nil** [comment]
No, we haven't written any scripts for this so far.

**Comment by SamiNorling** [comment]
After reviewing the "actor_type" attribute and its values, it is almost exclusively used as a workflow/note field, to denote where information is coming from (ULAN, Registration-Verified), not what type of actor it is. The few instances where the value is "Person" is just messy data that should really indicate the source, and there is no corresponding identification of "Organization" or "Corporate Body" or anything similar in the data set.

So I would say that this field actually does not need to be modeled.

**Comment by SamiNorling** [comment]
Related to my previous comment about the actor_type attribute, should I remove this field from our data if it is not to be mapped? We do plan to refresh our data before the end of the summer, and I can include removal of this field as part of my clean-up if not mapping a field that exists in the data is a problem.

**Comment by caknoblock** [comment]
There is no need to remove any fields that are not being mapped.  They will just be ignored.

**Comment by SamiNorling** [comment]
I suggest that this issue be closed.
