### ISSUE TITLE
ULAN ID reference model

### ISSUE THREAD

**Issue by mit2nil** [american-art/ima#13]
Hi,

Is there a reference model available for ULAN IDs? It is present in aac-actor.json.  As of now we are ignoring them because there are no reference models. Once we have the reference model, we can update our model. 

Nilay Chheda

**Comment by workergnome** [comment]
Yes—ULAN is a type of Linked Open Data identifier.   Please see http://review.americanartcollaborative.org/entity/E39_Actor#field_10-search_0

**Comment by mit2nil** [comment]
Hi David,

skos:exactMatch is not a valid predicate for class E39_Actor. Could you please verify if reference model for lod identifier is correct?

Nilay Chheda

**Comment by mit2nil** [comment]
I talked with @szeke and this is resolved. I have updated actor models with ULAN ids.

**Comment by workergnome** [comment]
Great!
