### ISSUE TITLE
Object_types vs Record_type

### ISSUE THREAD

**Issue by bsnikhila** [american-art/ima#15]
The objects file has 2 fields object_types and record_type. Should I model both of them? If so, how?
For now, I am modeling as [Classification](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_9-search_0) those values in object_types that have the corresponding record_type as "Visual Works:..."

**Comment by hlfloyd** [comment]
This looks like some inconsistent data in our CMS. There are 2869 instances of `"object_types": null,` in the objects json, and 48 with `"record_type": null,`. The record_type does not always start with "Visual Works:", and if it does it may not have corresponding object_types:
For example:
```
  "record_type": "Visual Works:  Sculpture",
  "object_types": null,
```
```
  "record_type": "Furnishings",
  "object_types": [
                "furnishings",
                "textiles",
                "bed coverings",
                "coverlets",
                "Jacquard coverlets"
  ],
```
```
  "record_type": null,
  "object_types": [
                "prints"
  ],
```
```
  "record_type": null,
  "object_types": [
                "prints",
                "color woodcuts"
  ],
```

**Comment by SamiNorling** [comment]
Is it possible to model both of those fields as sources for Classification values, which subsequently populate what is currently the repeatable "TYPE" field on the browse app?

After reviewing those fields, I've determined that they are essentially used interchangably in our system, with the difference being that "record_type" is more of a broad categorization that is almost always present, often beginning with "Visual Works: " followed by a general category such as "Sculpture," "Paintings," "Prints," etc. Compared to this, "object_types" tends to have more specific classifications as values, such as "oil paintings," "lithographs," etc., but as Heather noted, we have nearly 3,000 records where "object_types" is null, so even though that is, in my opinion, better information, only mapping that would leave us with many records lacking classification.

I would be interested to know what our options are for utilizing both fields. As part of the clean-up process, I could easily drop the "Visual Works: " portion of the "record_type" field to leave simpler values when I resubmit our data that would align better with other institutions' TYPE values.

If there cannot be two sources for Classification, then I will populate the null "object_types" with the broad categories found in "record_type" as part of my data clean-up, and you could then use "object_types" for Classification and leave "record_type" out of the mapping.

**Comment by SamiNorling** [comment]
I will be cleaning up our inconsistent use of object_types and record_types in our data, and will then map values in object_types to [Classification](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_9-search_0), without the logic that record_type must begin with "Visual Works:", as they are not related.

I suggest that this issue be closed.
