### ISSUE TITLE
departments are per-object

### ISSUE THREAD

**Issue by workergnome** [american-art/ima#16]
Every department is a unique URI:

http://data.americanartcollaborative.org/ima/object/id/8638/collection/department and http://data.americanartcollaborative.org/ima/object/id/863/collection/department are both the Prints department.

Please move to a thesaurus entry.

**Comment by bsnikhila** [comment]
Fixed it.

**Comment by workergnome** [comment]
I think the collections should be based on the department, not the object.

**Comment by bsnikhila** [comment]
Would this uri do for the Department?
http://data.americanartcollaborative.org/ima/object/id/8638/department
Or http://data.americanartcollaborative.org/ima/object/id/8638/physical_object
Or http://data.americanartcollaborative.org/ima/thesauri/department
Or something else?

**Comment by workergnome** [comment]
http://data.americanartcollaborative.org/ima/thesauri/department/prints seems most appropriate

**Comment by workergnome** [comment]
(And it appears you agree, as I check the data!  Thank you.)
