### ISSUE TITLE
Date Mapping

### ISSUE THREAD

**Issue by SamiNorling** [american-art/ima#21]
In reviewing our mappings, I think it's worth revisiting the mapping of our date fields, if possible. In the IMA's objects data, we have three creation date fields:

date_created
date_earliest
date_latest

Often, these fields have the same value (e.g. "1961") but sometimes date_created can be more descriptive with date_earliest and date_latest serving to set the date range. For example,

            "date_created": "20th Century\/2ND HALF",
            "date_earliest": "1951",
            "date_latest": "2000",

As our date fields are currently mapped, only date_earliest and date_latest are mapped to E52_Time-Span1, with the properties E82a_begin_of_the_begin and E82b_end_of_the_end, respectively, and it looks like the value of date_earliest is set as the label of E52_Time-Span1, and that is what populates Creation Date in the Browse app.

Would it be possible to use the value of date_created as the rdfs:label of E52_Time-Span1? This would make our visible dates more descriptive, while still having defined xsd:date values for begin and end of the time-span.

If this remapping is possible, my clean-up of our data leading up to the refresh will include a review of dates with that mapping in mind.

**Comment by caknoblock** [comment]
We can easily change the mapping for the label of Time-Span1, but I would want to get a confirmation from either David or Vladimir that this mapping is a reasonable thing to do in this case.

**Comment by workergnome** [comment]
That seems reasonable to me.

**Comment by SamiNorling** [comment]
Suggest this issue be closed. I will go ahead and apply this change in our updated mapping.
