### ISSUE TITLE
Purge before reload

### ISSUE THREAD

**Issue by workergnome** [american-art/ima#22]
Hey—It looks like when the new data was imported, the old data was not purged.  This means that I've got two versions of a lot of the information—for instance, homepages with and without slashes at the end, and two different URI patterns for dimensions.  It's making my poor code explode.

Can you make sure that you purge the existing data for IMA, and then reload this?

**Comment by workergnome** [comment]
see <http://data.americanartcollaborative.org/page/ima/object/13698>, particularly dimensions.

**Comment by GreatYYX** [comment]
Removed the old IMA data, rebuilt and imported the new data.
