### ISSUE TITLE
[data submission] Possible corrupted structure in JSON 

### ISSUE THREAD

**Issue by YinyiUSC** [american-art/ima#6]
When I tried to load the data into Karma, everything appeared to be in one single row, i.e. different objects are not distinguished. I haven't been able to open or view the JSON file in any of my text editors. But a possible cause might be that individual objects are not wrapped in curly braces. A sample segment would be:

[{
    "id" : 1,
    "title" : "abc",
    "artist" : "John",
},
{ 
    "id" : 2,
    "title" : "xyz",
    "artist" : "Allen",
}]

Would you please take a look at the JSON file that you submitted and possibly fix the structure? Thanks in advance.

**Comment by caknoblock** [comment]
Pedro told me this is a standard JSON format and we can restructure it using a program called jq.  When we meet next we can discuss this.

**Comment by jeremytubbs** [comment]
Yes it is valid JSON it is just difficult to browse... that was why my original data was split into multiple files.  You can browse the data in the closed issue: https://github.com/american-art/ima/issues/3

**Comment by YinyiUSC** [comment]
Okay thanks!
